"""add travel_date

Revision ID: 2ebee4dbbe11
Revises: 4c60b9c82d73
Create Date: 2026-01-21 22:31:33.888983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ebee4dbbe11'
down_revision = '4c60b9c82d73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('travel_date', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('travel_date')

    # ### end Alembic commands ###
